name: Build windows

on: [push]



jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\mingw64\bin\bash.exe --login '{0}'
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pacman -Syu
          pacman -S libtool autoconf automake make binutils filesystem e2fsprogs gcc libewf libjpeg-turbo ntfsprogs ncurses libncurses5 libncurses6 libncurses7 libncurses-devel libiconv zlib pkg-config
      - run: |
          cd ${GITHUB_WORKSPACE}
          chmod +x autogen.sh
          ./autogen.sh
      - run: |
          cd ${GITHUB_WORKSPACE}
          chmod +x compile.sh
          ./compile.sh
